# Generated by Django 4.1.6 on 2023-03-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('qualification', models.CharField(max_length=500)),
                ('banner', models.ImageField(upload_to='')),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('expired', models.BooleanField(default=False)),
                ('other_info', models.CharField(max_length=100)),
            ],
        ),
    ]
